### ISSUE TITLE
default face

### ISSUE THREAD

**Issue by slr772s** [DarthFennec/highlight-indent-guides#18] opened 2017-03-29 17:53 UTC
hi there,
I have installed the package one time from melp and one time by downloading it directly.
Also I have installed it on  ubuntu and Mac but I can't use it. 
every time I try it emacs show this massage:

**Error: highlight-indent-guides cannot auto set faces: `default' face is not set properly**

**Comment by DarthFennec** [comment] 2017-03-29 19:16
By default, `highlight-indent-guides` uses the theme's `default` face to calculate reasonable colors for highlighting the guides. Every theme should set this face. I'd like to know which theme you're using, and whether or not it works with other themes.

I've seen one other person who had an issue like this, and it was caused by an interfering `advice` he was using for something unrelated. I think it would be helpful if you tried running emacs with a minimal `.emacs` file, that just loads `highlight-indent-guides` and does nothing else. If that fixes the problem, there's probably something in your config or one of your other packages that's causing it.

Alternatively, you can also disable the auto-set feature and just set the colors manually in your config.

**Comment by slr772s** [comment] 2017-03-29 20:40
Thanks for support,

After lots of years of using VIM it's just some days I'm using EMACS so the init file doesn't contain lots of config. By the way my init file is here:

`;; Added by Package.el.  This must come before configurations of
;; installed packages.  Don't delete this line.  If you don't want it,
;; just comment it out by adding a semicolon to the start of the line.
;; You may delete these explanatory comments.
(package-initialize)

(require 'package)
(add-to-list 'package-archives '("org" . "http://orgmode.org/elpa/") t)
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages (quote (highlight-indent-guides w3 org org-plus-contrib))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

;;To add MELPA
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/"))
(when (< emacs-major-version 24)
  ;; For important compatibility libraries like cl-lib
  (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/")))

(require 'org)
(define-key global-map "\C-cl" 'org-store-link)
(define-key global-map "\C-ca" 'org-agenda)
(setq org-log-done t)

;; Disable the splash screen (to enable it agin, replace the t with 0)
(setq inhibit-splash-screen t)

;; Enable transient mark mode
(transient-mark-mode 1)

;; Enable Line Number
(global-linum-mode 1)
;; Add Space after numbers
(setq linum-format "%d ")
;; Add Line and space after numbers
;;(setq linum-format "%4d \u2502 ")

;; Configuration of highlight-indent-guides
(add-hook 'prog-mode-hook 'highlight-indent-guides-mode)
(setq highlight-indent-guides-method 'column)
`

**Comment by DarthFennec** [comment] 2017-03-29 21:56
Very strange ... I can't reproduce this. Even with your init file, it sets the faces just fine for me. And you say it does this in multiple operating systems? What version of emacs are you running?

**Comment by slr772s** [comment] 2017-03-29 22:38
I use emacs **25**

I saw your solution for someone else so I put this at the end of init file and know I can use it while actives perfectly and automatically on  JS,CSS,....  it doesn't active automatically in HTML .

```
(require 'highlight-indent-guides)

(setq highlight-indent-guides-auto-enabled nil)

(set-face-background 'highlight-indent-guides-odd-face "darkgray")
(set-face-background 'highlight-indent-guides-even-face "dimgray")
(set-face-foreground 'highlight-indent-guides-character-face "dimgray")
```

**Comment by DarthFennec** [comment] 2017-03-29 22:59
You have the line:
``` emacs-lisp
(add-hook 'prog-mode-hook 'highlight-indent-guides-mode)
```
But, I think `html-mode` and `xml-mode` derive `text-mode`, not `prog-mode`. So you'd also need:
``` emacs-lisp
(add-hook 'text-mode-hook 'highlight-indent-guides-mode)
```
Or at least:
``` emacs-lisp
(add-hook 'html-mode-hook 'highlight-indent-guides-mode)
```
And yes, disabling the auto-set feature and setting the faces manually is always an option. I just wish I knew why the feature wasn't working for you in the first place ...

**Comment by slr772s** [comment] 2017-03-29 23:47
I wished too.... 

**_Very special thanks for your kind support_**

**Comment by DarthFennec** [comment] 2017-03-30 16:28
Cool, glad the workaround works anyway. I guess I'll close this.

**Comment by DarthFennec** [comment] 2018-03-27 18:14
Hey, sorry to resurrect this, but I just had a thought. Are you running emacs in the terminal (`-nw`), or in its own gui window? I just found out that if I run it in a terminal, and 256 color support isn't available, I get this error. If that's the issue you were having, setting your `TERM` environment variable to `xterm-256color` might help.

**Comment by DarthFennec** [comment] 2018-04-02 19:38
It looks like this can also happen when running emacs as a daemon. See issue #32.

**Comment by DarthFennec** [comment] 2018-05-08 21:18
Closing again for inactivity. Feel free to reopen if you'd like.

**Closed by DarthFennec** 2018-05-08 21:18 UTC
Labels: question

**Comment by ihdavids** [comment] 2020-09-03 01:52
I am running into this as well.
I am running in termux on android with doom emacs / doom theme.

**Comment by nkichukov** [comment] 2022-09-02 16:16
same here, the workaround fixes the problem, it happens on GNU/Gentoo Linux with emacs version: 28.1 and also on ubuntu with emacs version: 26.3.
