### ISSUE TITLE
Highlight guide character is copied when yanking a region

### ISSUE THREAD

**Issue by eglyph** [DarthFennec/highlight-indent-guides#82] opened 2020-05-14 18:24 UTC
Steps to reproduce:
1. Set `highlight-indent-guides-method` to `'character'`
2. Enable `highlight-indent-guides-mode` in a buffer, make sure there are indentations displayed. 
3. Mark a region and kill it\kill-ring-save
4. Move the point and yank. 

Observe a region yanked with indicator characters. 

Emacs: GNU Emacs 26.3 (build 1, x86_64-apple-darwin19.3.0, NS appkit-1894.30 Version 10.15.3 (Build 19D76)) of 2020-03-06

Highlight-indent-guides-mode is installed from MELPA:
     ‘highlight-indent-guides-20200412.2328/’
     Version: 20200412.2328
     Commit: 1b12c7b440ff988c7237936187c1375ac4ddc7f4

**Comment by SreenivasVRao** [comment] 2020-05-20 15:29
yup, seeing the same behaviour with spacemacs 0.3, and emacs 26.3 NS version. will supply more details about packages - but did a package upgrade just this morning.

**Comment by DarthFennec** [comment] 2020-05-20 22:43
I'm running the `emacs-mac` package from brew, version 26.3. I'm not sure if this is the NS version or not. I can't seem to reproduce this at all. Any further information would be very helpful, thanks.

**Comment by andreas-roehler** [comment] 2020-05-28 19:04
May confirm the bug running GNU Emacs 28.0.50 (build 1, i686-pc-linux-gnu, GTK+ Version 3.14.5, cairo version 1.14.0) of 2020-05-20. The reason AFAIU: a string gets copied with its properties - so the display is yanked too.

**Comment by DarthFennec** [comment] 2020-05-28 19:39
>a string gets copied with its properties - so the display is yanked too.

@andreas-roehler That does happen, yes. However, as soon as the paste occurs, `jit-lock` will re-highlight the paste region. This triggers `highlight-indent-guides` to run on that region, which will delete the indicators and replace them with new ones that are suited to the new context. This all happens before the display is redrawn, so you should never see the old indicators after the paste, and they should certainly not stick around indefinitely.

Perhaps if `font-lock-mode` or `jit-lock-mode` is disabled for some reason, that might explain it, but as far as I'm aware those are on by default in pretty much all editing modes. I suppose that's something for you to check, though.

**Comment by SreenivasVRao** [comment] 2020-05-28 21:29
Fwiw, I notice this happen when I paste into scratch buffer. That's
fundamental mode.

**Comment by DarthFennec** [comment] 2020-05-28 21:51
Hm, strange. My scratch buffer is `lisp-interaction-mode`, but even if I open a file in `fundamental-mode` I still don't get the issue. Are you also seeing this in modes other than `fundamental-mode`?

If I turn off `jit-lock-mode`, my indicators stay around on yanked lines, but also when I create new lines, they don't have any indicators at all (and modifying lines won't update indicators). Is all of this consistent with what you're seeing?

**Comment by andreas-roehler** [comment] 2020-06-01 15:11
Maybe replace the setting of a text-property by an overlay-property? 
Reading the following in Elisp Info: 

* 39.16 The ‘display’ Property
============================

The ‘display’ text property (or overlay property) is used to insert
images into text, and to control other aspects of how text displays.
The value of the ‘display’ property should be a display specification,
or a list or vector containing several display specifications.  Display
specifications in the same ‘display’ property value generally apply in
parallel to the text they cover.

* 39.9.2 Overlay Properties
-------------------------

Overlay properties are like text properties in that the properties that
alter how a character is displayed can come from either source.  But in
most respects they are different.  *Note Text Properties::, for
comparison.

   Text properties are considered a part of the text; overlays and their
properties are specifically considered not to be part of the text.
Thus, copying text between various buffers and strings preserves text
properties, but does not try to preserve overlays.

**Comment by DarthFennec** [comment] 2020-06-01 22:01
I've considered this numerous times, and I'm starting to think I should just knuckle down and do it. Technically that's the expected way to implement something like this, and there are a good handful of issues that would be fixed if I did this, this issue included. The reason I haven't done it is that, because of the way emacs implements overlays, they can be quite a bit slower to use than text properties, especially if you have a lot of them like this.

I don't know exactly how much lag this will introduce, but I'd rather not deal with it if I can help it. However, the more issues I see that could be fixed by using overlays, the more I think that maybe some extra lag is worth it, as long as it doesn't end up being too much. Maybe I'll start looking into it after I've finished optimizing the bitmap display method.

**Comment by andreas-roehler** [comment] 2020-06-02 05:50
WRT speed: Maybe it's preferable advising copy-region-as-kill in order to remove the 'display property?

**Comment by DarthFennec** [comment] 2020-06-02 18:07
Well as I said, there are a handful of other issues that would be fixed by switching to overlays, so I'll still consider doing that. But yeah, your idea is a good bandaid solution for this particular issue. Maybe it would make more sense to advise `insert-for-yank` instead though, like:

``` emacs-lisp
(defadvice insert-for-yank (before my-clear-indent-guides activate)
  (remove-text-properties
   0 (length (ad-get-arg 0))
   '(display highlight-indent-guides-prop) (ad-get-arg 0)))
```

Since I can't reproduce the issue, you'll have to check if that works for you. If it fixes the problem, feel free to leave it in your config for the time being. I don't think I'll be integrating it into the mode, since as far as I'm aware you three are the only ones having this problem, and for everyone else it would just be redundant.

**Comment by SreenivasVRao** [comment] 2020-06-02 18:26
I just tried this, and it works. Thanks @DarthFennec! :)

https://xkcd.com/1172/ is appropriate I think!

**Comment by andreas-roehler** [comment] 2020-06-03 07:45
Works for me, thanks.

**Comment by prashantvithani** [comment] 2020-06-03 08:15
I was having the same issue and been following this thread. Solution provided in https://github.com/DarthFennec/highlight-indent-guides/issues/82#issuecomment-637715626 works for me. Thanks @DarthFennec!

**Comment by andreas-roehler** [comment] 2020-06-03 09:19
BTW being meanwhile concerned WRT envisaged use of overlay-property. As it's told being slow due to exponential growth, enabling the mode with large files may turn nasty.

**Comment by DarthFennec** [comment] 2020-06-03 15:58
@andreas-roehler Agreed. One of these days I'll just have to do it and see how bad it turns out to be.

**Closed by DarthFennec** 2020-06-03 15:59 UTC
Labels: bug

**Comment by Matafou** [comment] 2021-04-07 00:26
For the record I am also having this issue (version 20200820.2328, emacs 28.0.50) but only in `emacs-lisp` mode and only when enabling `highlight-indent-guides` by a hook. When I enable the mode by hand I don't have this issue.
It looks a bit like the workaround explained here: https://github.com/DarthFennec/highlight-indent-guides/issues/15#issuecomment-300233767, but it does not depend on the place of h-i-g in the hook.
