### ISSUE TITLE
Indent guides disappears after a specific point in file

### ISSUE THREAD

**Issue by CSRaghunandan** [DarthFennec/highlight-indent-guides#7] opened 2016-11-12 05:28 UTC
<img width="631" alt="screen shot 2016-11-12 at 10 54 05 am" src="https://cloud.githubusercontent.com/assets/5226809/20235893/8fbcadc2-a8c6-11e6-8acb-c1facbff6652.png">

I'm not sure what exactly is happening here. I'd have to delete the line my cursor is on to get back the indent guides for the buffer.
Can you please check if you can reproduce this bug (for `rust-mode`). I'm not sure the problem is with `rust-mode` or `highlight-indent-guides`. Text from the image :- http://pastebin.com/bDadDK5S

**Comment by DarthFennec** [comment] 2016-11-14 19:43
This is very strange ... I can reproduce it, but only in `rust-mode`, and only with the file you provided (every other Rust file I've tried so far works fine). When I do `revert-buffer` it fixes it, or when I edit some parts of the file.

From the limited testing I'm able to do right now, it seems that emacs is only running the calculation function I've hooked into `jit-lock` for the first so many lines; The rest of the code isn't being highlighted simply because emacs never tells `highlight-indent-guides` to highlight it. I don't know why this would be happening, but I doubt it's something I'm doing. It may be an unintended side-effect of something in `rust-mode`, but I don't know enough about that mode to tell for sure. I'll look more into it and try to determine if `rust-mode` is doing anything weird.

Thanks for letting me know.

**Comment by DarthFennec** [comment] 2017-01-17 00:18
I've been giving this a quick look every so often ever since you submitted it, with no luck whatsoever. But today I've finally cracked it.

The problematic function is `rust-mode`'s `rust-font-lock-extend-region`. Relevant section:

``` emacs-lisp
(save-match-data
  (goto-char font-lock-beg)
  (while (and (< (point) font-lock-end)
              (re-search-forward rust-re-non-standard-string (buffer-end 1) t)
              (<= (match-beginning 0) font-lock-end))
    (setq font-lock-end (max font-lock-end (match-end 0)))
    (goto-char (1+ (match-beginning 0)))))
```

The purpose of this function appears to be to force `font-lock` to extend its string matches to include the prefix and suffix characters for raw string literals (`r" ... "`). The problem is with the part above, which attempts to match a raw string in the buffer, and if it finds one, it extends the `font-lock` region to the end of the match.

The thing is, there are no raw strings in the buffer you're working with here, but the `rust-re-non-standard-string` regex still matches. What seems to happen is, if it finds an opening raw string indicator and no closing indicator, it just matches to the end of the buffer. I believe this interferes with `jit-lock` running on the same section, which is why `highlight-indent-guides` never runs beyond this point.

Of course, if there is an opening raw string indicator and no closing indicator, the reasonable thing to do is highlight the rest of the buffer as a string, so I think that behavior is intentional. But again, there are no raw strings in this buffer. What is actually being matched is the `r"` at the end of `"ArcadeRS Shooter"`, because it's a dumb regex and doesn't take context such as "is this already inside a string or comment" into account. So, this is a bug in `rust-mode`.

I reported it [here](https://github.com/rust-lang/rust-mode/issues/192).

**Comment by DarthFennec** [comment] 2017-04-11 16:29
@CSRaghunandan This should now be fixed in `rust-mode`. If you could verify, that would be fantastic.

**Comment by CSRaghunandan** [comment] 2017-04-12 06:11
@DarthFennec highlight-indent-guides is working fine now on the same file 👍 
Thanks

**Comment by DarthFennec** [comment] 2017-04-12 16:23
Cool! Closing this, then.

**Closed by DarthFennec** 2017-04-12 16:23 UTC
