### ISSUE TITLE
Strange behavior of indent highlighting after changing an indented region

### ISSUE THREAD

**Issue by 0rdy** [DarthFennec/highlight-indent-guides#15] opened 2017-02-16 06:59 UTC
Sometimes when I write or format text in Emacs, indent highlighting breaks down, i.e. my indent character loses default highlight-indent-guides-character-face:
![1487227467](https://cloud.githubusercontent.com/assets/9018005/23010503/7dd08aa8-f424-11e6-93e3-e76bab8addb5.png)

My settings:
```
(use-package highlight-indent-guides
  :config
  (setq highlight-indent-guides-method 'character)
  ;; Indent character samples: | ┆ ┊
  (setq highlight-indent-guides-character ?\┆)
  (add-hook 'prog-mode-hook 'highlight-indent-guides-mode))
```
Is this a bug?

**Comment by DarthFennec** [comment] 2017-02-16 17:50
Oh weird, I've never encountered this ... could you give a specific example that I can try to reproduce? What version of emacs are you using? It's also possible that a minor mode you're using is interfering somehow, I would suggest trying to run emacs with just `highlight-indent-guides` loaded and see if you still get this behavior.

**Comment by 0rdy** [comment] 2017-02-16 18:49
@DarthFennec, I'm using Void Linux and Emacs version 25.1.1.

Well, I created empty `~/emacs.d` directory with the following `init.el`:
```
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)

(require 'cl)

(require 'highlight-indent-guides)
(setq highlight-indent-guides-method 'character)
(setq highlight-indent-guides-character ?\┆)

(setq highlight-indent-guides-auto-enabled nil)
(set-face-background 'highlight-indent-guides-odd-face "orange")
(set-face-background 'highlight-indent-guides-even-face "orange")
(set-face-foreground 'highlight-indent-guides-character-face "orange")

(add-hook 'prog-mode-hook 'highlight-indent-guides-mode)
```
As you can see on my screenshot result still the same, i.e. the third level loses built-in default face.
![1487269540](https://cloud.githubusercontent.com/assets/9018005/23035149/dd4a9f98-f486-11e6-90fc-d96c26a60516.png)

To reproduce you should delete or put some extra whitespaces inside a function body before the second indentation level(or even the first). The test example to reproduce:
```
(use-package test
         :config
         (do-some-stuff-here)
         (do-some-stuff-here))
``` 

Btw, this test shows me a bug appears only with Elisp code, i.e. Clojure-mode and .cpp works normally.

**Comment by DarthFennec** [comment] 2017-02-17 00:01
Hmm ... I'm getting something slightly different:

![2017-02-16-131025_334x123_scrot](https://cloud.githubusercontent.com/assets/1480189/23041325/6dd4dae4-f449-11e6-892b-efb83bb96665.png)

If I disable `highlight-indent-guides` in that buffer, and then re-enable it, it works as expected, which makes me think something isn't initializing properly during the hook. Actually ... I think I just found it.

`highlight-indent-guides` needs the `display` property to be managed by `font-lock`, otherwise emacs won't remove guide characters when they become invalid. That seems to match the behavior both of us are seeing, because there are just extra guides laying around where there shouldn't be. To get `font-lock` to manage this property, the mode adds `display` to `font-lock-extra-managed-props`, like so:

```emacs-lisp
(add-to-list 'font-lock-extra-managed-props 'display)
```

When I double check the value though, I see:

```
font-lock-extra-managed-props is a variable defined in ‘font-lock.el’.
Its value is (help-echo)
Local in buffer .emacs; global value is (display)
```

Presumably this is happening because the major mode (which sets this variable to `(help-echo)`) is executing after `highlight-indent-guides` initializes. I've verified that this certainly appears to be the case, though I have no idea why it might be happening. I'll continue to look into it.

Thanks for bringing this up.

**Comment by DarthFennec** [comment] 2017-05-09 17:05
Sorry I haven't responded to this in a while, I haven't had much time to look into it more.

If you check the value of the `prog-mode-hook` variable (<kbd>C-h v prog-mode-hook RET</kbd>), you'll see a list of hooks that are run when `prog-mode` begins, which should include `highlight-indent-guides-mode`. I've just discovered that, at least for me, this issue only seems to occur when `highlight-indent-guides-mode` is the first element of this list. If it's the second element or later, that appears to fix the issue. So, if you have other things in that hook, just make sure that you `add-hook` them later in your `init.el` than `highlight-indent-guides-mode`.

Please tell me if this helps. Thanks.

**Comment by 0rdy** [comment] 2017-05-09 17:30
Honestly, I haven't met a similar behavior after open the issue. Yes, now I got the following value
`(fic-mode nlinum-mode highlight-indent-guides-mode rainbow-delimiters-mode highlight-numbers-mode)` of prog-mode hook and highlight-indent-guides-mode  works without this bug. 

Thanks for the response.

**Comment by DarthFennec** [comment] 2017-05-09 17:35
Cool, I'm glad. I'll close this now, then.

**Closed by DarthFennec** 2017-05-09 17:35 UTC
Labels: bug
