### ISSUE TITLE
indention highlight shadowed by hl-line-mode

### ISSUE THREAD

**Issue by Dickby** [DarthFennec/highlight-indent-guides#10] opened 2017-01-02 17:20 UTC
I don't know if it's changeable, but I would prefer the indention-highlight to have a higher priority than hl-line-mode.
As I understood this package doesn't use overlays, so it might be not as simple as changing the priority.
Feel free to close this issue if it's not possible.
Thanks.

**Comment by DarthFennec** [comment] 2017-01-03 20:01
As much as I like the idea, I'm pretty sure it's impossible. The emacs documentation states that "all overlays take priority over text properties", which seems pretty clearly to imply that there's no intention of allowing text properties to take priority. I'll close this issue, then. Sorry about that.

**Comment by Dickby** [comment] 2017-01-03 20:17
It's strange, i reallized that in some lines the indention-highlighting isn't shadowed by hl-line, in some others it is, in again others only one of the indention-highlight columns are.
Anyways it's a nice package, thanks for that.

**Comment by DarthFennec** [comment] 2017-01-03 20:45
Yeah, I've noticed this as well. What I believe happens is, when I set the `display` text property to a string that has faces in it, the faces in the string take precedence over everything else, for some reason. There is no mention of this anywhere in the documentation, so I'm pretty sure it's a bug in emacs. The reason it only shows up sometimes is because I only use `display` when I need to color a tab character that spans multiple indentation levels. So, it won't happen with spaces, or tabs that are a single solid color.

While it would be possible to leverage this to achieve the behavior you're looking for, I'm apprehensive about doing so. Assuming it is a bug, there's a good chance it will get fixed at some point, which would break the feature anyway. Also, there are potential performance issues with rendering most of the whitespace in a buffer as `display` strings, and I don't think something like this is worth trading away performance. So technically it is possible, but it relies on an apparent bug to work, and I'm not comfortable with relying on bugs.

**Comment by DarthFennec** [comment] 2017-01-11 19:49
After discussing it with a maintainer, I've discovered that this is apparently not a bug after all, but intended behavior that will probably never change. What seems to happen is, the overlay is applied first, to give it a chance to override the `display` property on the text, and because of this, the `display` property will always take priority over any overlays. So, it would be possible to use this behavior to achieve what you're going for. However, I still feel apprehensive about doing so, partially because it may or may not introduce a performance hit, and partially because it just seems ... hacky.

I've come up with a simpler way to do what you requested. Note that this will only look good if you're using the `fill` display method. The idea is that, instead of drawing both the line highlight and the guides, and somehow getting the guides to take priority, we can just tell `hl-line-mode` to not draw the overlay on indentation in the first place. This can be done by customizing `hl-line-range-function`, like so:

``` emacs-lisp
(defun my-hl-line-range-function ()
  (let ((lbp (line-beginning-position)))
    (cons (if (get-text-property lbp 'highlight-indent-guides-prop)
              (save-excursion (back-to-indentation) (point))
            lbp)
          (line-beginning-position 2))))
(setq hl-line-range-function 'my-hl-line-range-function)
```

This code isn't really optimized to my liking, but it should work just fine for you. I may add it to the mode later if I can get it the way I want. Let me know what you think.

**Comment by Dickby** [comment] 2017-01-12 15:56
I actually use the `'culumn` display method.
I started to use the new look anyways, and i prefer it over the old one.
Thanks for looking into it again.

**Comment by DarthFennec** [comment] 2017-01-12 17:45
The "new look"? I'm not sure what you mean by that.

**Comment by Dickby** [comment] 2017-01-12 18:03
with your `my-hs-line-range-function`, the hl-line overlay starts after the indentation-whitespace was what i called "new look".

**Comment by DarthFennec** [comment] 2017-01-12 19:45
Ah, got it, thanks for clarifying. So you're happy with the way that looks with the `column` method, then? In that case, I think this can be closed now.

**Closed by DarthFennec** 2017-01-12 19:45 UTC
