### ISSUE TITLE
very slow when entering strings

### ISSUE THREAD

**Issue by olagrottvik** [DarthFennec/highlight-indent-guides#33] opened 2018-05-05 10:49 UTC
When editing strings (i.e. writing s = '\n') in a Python file with a lot of strings, the operation of adding ' makes highlight-indent-guides take forever.

This is the result of elp-instrument-package highlight-indent-guides- when writing s = '\n' in the buffer:
[results.txt](https://github.com/DarthFennec/highlight-indent-guides/files/1976561/results.txt)

highlight-indent-guides--guide-region                           14          5.2656013           0.3761143785
highlight-indent-guides--get-guides                              109         0.0021589999     1.980...e-05
highlight-indent-guides--guide-line                                82          0.0021178           2.582...e-05
highlight-indent-guides--column-keyword-matcher      428         0.0017428999     4.072...e-06
highlight-indent-guides--get-prev-guides                      14          0.0014244000      0.0001017428
highlight-indent-guides--character-highlighter             400         0.0006692999      1.673...e-06
highlight-indent-guides--calc-guides                              95          0.0001826999      1.923...e-06

5 second total freeze of emacs 

Would it be possible to add a feature for either:

- only update at certain occasions (new line)
- only update after a certain timeout

Greatly appreciate the package overall, but this makes writing code efficiently somewhat hard.

**Comment by DarthFennec** [comment] 2018-05-07 17:37
Could you tell me which Python major mode you're using? I don't get this behavior in `python-mode` or `python.el`. It also might help to know what other minor modes you have loaded.

`highlight-indent-guides` is tied to `font-lock`, and only runs when and where `font-lock` decides to update highlighting. In general this should be very quick and responsive, since that's what `font-lock` is designed to be good at. There's also no reason for string literals in particular to cause a problem like this, since `highlight-indent-guides` doesn't care what characters you're typing or what kind of syntax they have (except in some cases when using multiline strings). The calculations themselves are pretty cheap too, especially since `font-lock` only feeds it about ten lines at a time in general. All things considered, I'd be very surprised to find that `highlight-indent-guides` is stalling for five whole seconds on its own accord. This seems like a situation where something else in your configuration is causing `font-lock` to trigger way too many times in a row, causing `highlight-indent-guides` to re-run over and over. Or something like that, anyway.

I'd like to see what happens if you try this on a clean default emacs configuration, with only `python.el` and `highlight-indent-guides` loaded. If this fixes the issue, then we know the cause was something else you have loaded, and we can try to narrow the cause down from there.

**Comment by olagrottvik** [comment] 2018-05-10 10:04
Thanks for responding so quickly!

So I've tried the following:
emacs --no-init

Evaled the following:
(require 'package)
(package-initialize)
(require 'highlight-indent-guides)

And enabled the mode in the following file: 
https://github.com/olagrottvik/uart/blob/master/uart/bus.py

describe-mode gives me the following:
Enabled minor modes: Auto-Composition Auto-Compression Auto-Encryption
Diff-Auto-Refine Eldoc Electric-Indent File-Name-Shadow Font-Lock
Global-Eldoc Global-Font-Lock Highlight-Indent-Guides Line-Number
Menu-Bar Mouse-Wheel Override-Global Shell-Dirtrack Tool-Bar Tooltip
Transient-Mark

+ Python major mode. I'm not quite clear how to figure out which version of this mode I'm using - but everything should be standard. I'm using a self-compiled Emacs 26.1-rc1.

I'm still experiencing very slow updates as can be seen in the following screen capture.
1. adding a string without highlight-indent-guides mode
2. then enabling the mode and we see a significant delay from keyboard input to actual screen update

![screen_capture](https://user-images.githubusercontent.com/6538308/39864365-a3db5396-5449-11e8-9760-e47066b96f25.gif)

However, by turning off Python-mode (i.e. replacing with prog-mode), the delay disappears.

Please let me know if there are more information I can provide you!

**Comment by DarthFennec** [comment] 2018-05-10 19:43
Great, thanks! I can reproduce this now. A few things I notice right off the bat:

- The behavior is more prominent with larger files than with smaller ones.
- The behavior is more prominent near the beginning of a file than near the end.
- When a single open quote is added to the buffer, the entire remainder of the buffer is reformatted as if it were one big string.

From here, the issue is pretty clear I think:

- `highlight-indent-guides` has logic to not insert guides on lines that are continuations of multiline strings or comments.
- `python.el` for some reason highlights all strings as if they are multiline, even though they are not.
- Therefore, when you add an open quote without a closing one, the rest of the buffer gets treated as a string, which causes `highlight-indent-guides` to remove all the guides from the remainder of the buffer. If the buffer is big, this can take a really long time.
- The reason I haven't noticed this issue is because I use `electric-pair-mode`, so when I type a quote it gets closed automatically before any syntax highlighting is performed.

The first thing you might consider doing (even just as a temporary workaround) is turning on `electric-pair-mode`. Personally, I find this mode indispensable for editing anything (auto pairing, auto indentation, and syntax highlighting are my holy trinity of "absolutely necessary for comfortable coding"). The fact that it alleviates this issue is just a bonus. Your mileage may vary, obviously.

There appear to be two issues here. The first is that emacs is highlighting a single-line string as if it were multiline. At least I thought this was an issue, I'm not so sure now. I've tested this with a number of languages: it incorrectly highlights past the end of the line in Python, Javascript, Java, Groovy, HTML, Bash, and others. The only mode I tried that handles this correctly is Haskell, which is third-party. I'm getting the feeling that emacs just treats all strings as multiline by default for some internal or historical reason. Perhaps it's just because all strings in elisp are multiline? Whatever the case, it doesn't seem like there's much to do about it.

The second issue is obviously `highlight-indent-guides` redrawing the entire buffer. I'll try to look into what can be done about this, but I'm not sure how much success I'll have. Currently, my thoughts are:

- Remove the restriction that guides should not show inside strings or comments. I'm unwilling to do this, since there are good reasons for it to be like this, and changing it will just introduce a bunch of new bugs and strange behavior.
- Only redraw the visible parts of the buffer. This is something I've looked into before for general performance reasons, but there doesn't seem to be a good consistent way to do it, beyond "just let `jit-lock` handle it" which is what I'm already doing.
- Right now, a redraw will extend itself down to the first line it finds that already has correct guides. A comment or string line with no guides does not currently count for this. If it did, that would speed up the typing of the characters inside the string itself. However, it would not speed up the quote characters, and it would introduce weird bugs with some indentation not being updated properly.

So that's three non-options, which isn't so useful. I'll keep thinking, though.

**Comment by olagrottvik** [comment] 2018-05-11 07:38
Thanks for your very thorough examination of your problem - and also thanks for the electric-pair-mode suggestion. This mode is solving my issues now - and I'll leave it up to you to close this issue.

I agree that any of the modifications to highlight-indent-guides probably will just add other bugs and issues. However, maybe you can consider a timeout variable? Or different kinds of triggering? E.g. [flycheck](http://www.flycheck.org/en/latest/user/syntax-checks.html#check-automatically) uses different kinds of triggering + a variable to delay to start evaluating the buffer.

**Comment by DarthFennec** [comment] 2018-05-11 17:12
Not sure exactly what you mean by "timeout variable". If you're talking about setting a timer to cancel/interrupt the operation after a certain amount of time, I suppose that might help, as long as it can be resumed later. It would calculate a small batch of lines at a time, and give the IO loop some time to run in between each batch, which would at least keep emacs from freezing. Not sure how well that would interact with newer runs of the same function running in parallel ... I'd have to think on it.

If instead you're talking about waiting to start the operation until after a countdown timer/idle timer triggers, I don't know if that would help much. You'd still get the same problem (just delayed) unless you were able to type the entire string literal before the timer runs out/in one go, which very rarely happens (at least for me).

Different kinds of triggering is an interesting idea, but I think it's simplest to stick with `jit-lock`. In the general case, `jit-lock` is by far the best fit for this kind of thing, so changing the triggering mechanism would only limit things. Alternatively, adding another trigger alongside `jit-lock` would just make things too complicated I expect, and cause more problems.

I understand that this can be a real issue, especially since most emacs modes appear to treat all strings as multiline for whatever reason. But this issue has existed since the beginning, and you're the first person to say anything about it. That tells me that most people aren't having this problem (I expect that most people use `electric-pair-mode` or something similar).

I will continue to think on this, and if I come up with something I like I'll add it. But for now I think I'll close this issue. Thanks!

**Closed by DarthFennec** 2018-05-11 17:12 UTC
Labels: question

**Comment by vab2048** [comment] 2020-01-17 14:09
I have come across this issue when editing a large org mode file as well.

The suggestion of turning on electric-pair-mode still does not fix the issue.

Is there any other advice you can give to avoid running into this issue?

**Comment by phisu** [comment] 2021-05-02 15:36
i have a similar problem with large [php files](https://github.com/seagle0128/.emacs.d/issues/304) and i had little luck with electric-pair-mode. so i did some experiments with the emacs cpu profiler. only when i turn off the following modes i get a tolerable perfomance, so i can type and only have to wait a few seconds until i get the quotation mark displayed.

highlight-indent-guides-mode
font-lock-mode
electric-pair-mode

i'm thinking of writing a macro where i turn off all three modes so i can insert quotes and then turn the modes back on with a macro. but i think that's a very dirty hack. do you have any further thoughts on this problem? maybe it's possible to introduce a delay so that you can type faster than highlight-indent-guides-mode turns on.
