### ISSUE TITLE
Show indentation of empty lines

### ISSUE THREAD

**Issue by thblt** [DarthFennec/highlight-indent-guides#19] opened 2017-03-30 19:08 UTC
Highlight-indent-guides don't show any indentation level on empty lines, which I believe could be useful.  In the example below, lines 9 to 11 are empty: indent-guide shows indent markers on them, but highlight-indent-guide doesn't.

![2017-03-30-210521_1270x710_scrot](https://cloud.githubusercontent.com/assets/2453136/24521488/9b85ddc6-158c-11e7-9cad-9bffba84fd9a.png)

If indent-guide's solution to this problem may be of any interest, the relevant issue is here: https://github.com/zk-phi/indent-guide/issues/51

Thanks!

**Comment by DarthFennec** [comment] 2017-03-30 23:59
I agree that this would be a nice feature. There are a few reasons I never bothered with it:

- When calculating for an empty line, I have a choice: I can copy the guides used above the line, or the ones below it. But which is more correct? In some languages (C, Java, Ruby, etc) code blocks are followed by a special 'end block' line, and empty lines preceding that line are part of the block, so in this case, the guides above the empty lines should be used. Although, for the same reason, if the first line of the block is empty, the guides below that empty line should be used instead. Maybe the direction with more indentation should be used, then? But, in other languages (Python, Lisp, Haskell, etc) code blocks aren't terminated with a special line. Clearly, using the guides below is more correct here, because otherwise, guides would just overflow into the empty lines between functions. The point is, however you choose to do it, it'll end up looking wrong somewhere. Not highlighting empty lines at all avoids this problem.
- It looks like the approach zk-phi took was to hardwire a set of "lispy" languages into the code, and treat those major modes differently. I don't like language-specific solutions like this, because there are always bound to be major modes that you didn't know about, or missed, or otherwise forgot to put on your list, and it still looks wrong in those languages. Whenever possible, I prefer a cleaner, more general solution that behaves the same way everywhere.
- By definition, indentation is the whitespace preceding a line of code. Therefore, if there is no code on a line, there is no indentation to highlight. This is also why `highlight-indent-guides` doesn't put guides inside of multiline strings or comments. Putting guides in those places is not accurate, it's less clear what's actually going on, and for that reason I just don't think it looks very good.
- Most importantly, I don't think it's possible to do this without fundamentally changing `highlight-indent-guides` at its core. This mode was designed to be fast, and a sizable part of that is the fact that it uses `font-lock` (which is designed to highlight text extremely quickly), rather than spawning thousands of comparatively heavy overlay objects like other modes do. While the `font-lock` approach is very fast, it also comes with its share of small inconveniences. For example, since guides are displayed by `font-lock`, they cannot exist unless there is a character to display them. This means guides simply cannot be displayed on empty lines, since there is no whitespace there to highlight.

Since zk-phi decided to use overlays, `indent-guide` can put guides anywhere. While that is a benefit, I personally feel that it isn't a very important one. I certainly don't think it's worth the performance benefit of using `font-lock`.

**Comment by thblt** [comment] 2017-03-31 13:45
First, thanks a lot for the detailed answer.  Since you haven't close the issue,  I assume such an option is not totally out of discussion, so I'll try and answer some of your points.

**Indent an empty line surrounded by different indentation levels.**  I've given this a bit of thought, and a think  `indent_level = min(above_indent_level, below_indent_level)` is perfectly valid, because even if, in block-based languages, the block may not actually be over at the last contents line, the block is not really what matters.  The indent markers going back one level clearly indicate that the block *contents* are over, which is IMO more important than the actual delineation of the actual block.  That's what `indent-guide` does, and it seems reasonable.

**Font-lock vs overlays**.  I have no experience with programming with Emacs overlays, and my experience with faces is restricted to theming, so I'm not going to argue here.  Just wanted to ask if it would be *theoretically* possible to use overlays in empty lines?   I could try and give it a look when I have the time.
   

Thibault

**Comment by DarthFennec** [comment] 2017-03-31 18:55
Your first point is valid. That's probably the best option, even though I personally still think it looks weird. Then again, I think putting empty lines immediately before block closers looks weird to begin with, so maybe it's just me.

I'll admit I haven't actually tried to use overlays for this mode, but I have noticed performance issues with modes that do use a lot of them. Also, the [documentation](https://www.gnu.org/software/emacs/manual/html_node/elisp/Overlays.html) makes the following statement:

> The visual effect of an overlay is the same as of the corresponding text property (see Text Properties). However, due to a different implementation, overlays generally don’t scale well (many operations take a time that is proportional to the number of overlays in the buffer). If you need to affect the visual appearance of many portions in the buffer, we recommend using text properties.

This makes sense, as overlays are implemented as a zipper list as far as I can tell, and emacs has to sift through the entire list in order to get to a particular overlay. Also, since all overlays in a buffer are stored in the same list, if you have multiple modes that are heavy on overlays, they would all slow each other down even more. Compare this to text properties, controlled by `font-lock`, which are always immediately available from the character in question.

It would certainly be possible to use overlays for empty lines, and `font-lock` for everything else, but I'm averse to the idea. Doing this would complicate the code considerably, and make my life a good deal more difficult. I run into enough weird edge case issues with `font-lock` on its own, and using overlays on top of that would basically double those issues. So, I'd much rather stick with one or the other.

What it basically comes down to is, I simply don't think this issue (feature?) is important or useful enough to justify the problems associated with fixing it, unless we find a safe and simple way to do it. I didn't close the issue immediately because I'm always willing to discuss and be proven wrong about these things, but I simply don't see a way to do this that I would consider to be worth the downsides.

**Comment by thblt** [comment] 2017-03-31 20:12
Thanks a lot, again, for the detailed replies.  I guess we can close this, then.

**Comment by DarthFennec** [comment] 2017-03-31 20:17
I guess so. I'll keep this in mind though, in case things change in the future. Thanks for opening the issue!

**Closed by DarthFennec** 2017-03-31 20:17 UTC

**Comment by Atemu** [comment] 2021-04-01 12:28
Aren't there context-sensitive function built into major modes that could be used to get the correct indent for a blank line?

Most major modes allow me to jump to the right place by hitting `TAB` on an empty OOTB.

Something else I just thought of: Would it be feasible to modify the buffer text itself to insert actual indentation characters in empty lines and then remove them again for actions like writing the file or killing a region?
